---
- hosts: monitors
  remote_user: root

  tasks:
    - name: Install packages
      apt:
        name: "{{ items }}"
      become: true
      vars:
        items:
          - python3-pip
          - python3-venv


- hosts: monitors
  remote_user: pi

  vars:
    basedir: /home/pi/thenose
    confdir: /home/pi/.config/thenose
    venv: "{{basedir}}/venv"

  tasks:

    - name: Create directories
      file:
        path: "{{ item }}"
        state: directory
      loop:
        - "{{ basedir }}"
        - "{{ confdir }}"

    - name: setup venv
      command: "python3 -m venv --system-site-packages {{ venv }}"
      args:
        creates: "{{ venv }}"

    - name: upgrade pip
      command: "{{ venv }}/bin/pip install pip --upgrade"
      register: pip_upgrade
      changed_when: "False == (pip_upgrade.stdout | regex_search('already up-to-date'))"


    - name: Install project directory contents
      copy:
        src: "{{ item.file }}"
        dest: "{{basedir}}/{{ item.file }}"
        mode: "{{ item.mode }}"
      loop:
        - file: measure.py
          mode: '0755'

        - file: requirements.txt
          mode: '0644'

    - name: Install python packages
      pip:
        requirements: "{{basedir}}/requirements.txt"
        virtualenv: "{{ venv }}"


    - name: Write configuration
      template:
        src: templates/config.yaml.j2
        dest: "{{confdir}}/config.yaml"


- hosts: monitors
  remote_user: root

  tasks:
    - name: Install Systemd script
      copy:
        src: files/thenose.service
        dest: /etc/systemd/system
        mode: '0755'
        owner: root
        group: root
      notify:
        - reload systemd
        - restart service

  handlers:
    - name: reload systemd
      become: yes
      systemd:
        daemon_reload: yes

    - name: restart service
      become: yes
      systemd:
        name: thenose
        enabled: yes
        state: restarted
