---
- hosts: monitors
  remote_user: pi

  vars:
    basedir: /home/pi/thenose
    confdir: /home/pi/.config/thenose
    venv: "{{ basedir }}/venv"

  tasks:
    - name: Install packages
      ansible.builtin.apt:
        name: "{{ items }}"
      become: true
      vars:
        items:
          - python3-pip
          - python3-venv
      tags:
        - never
        - install

    - name: Create directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ basedir }}"
        - "{{ confdir }}"
      tags:
        - never
        - install

    - name: setup venv
      ansible.builtin.command: "python3 -m venv --system-site-packages {{ venv }}"
      args:
        creates: "{{ venv }}"
      tags:
        - never
        - install

    - name: upgrade pip
      ansible.builtin.command: "{{ venv }}/bin/pip install pip --upgrade"
      register: pip_upgrade
      changed_when: "False == (pip_upgrade.stdout | regex_search('already up-to-date'))"
      tags:
        - never
        - install

    - name: Install project directory contents
      ansible.builtin.copy:
        src: "{{ item.file }}"
        dest: "{{ basedir }}/{{ item.file }}"
        mode: "{{ item.mode }}"
      loop:
        - file: measure.py
          mode: '0755'

        - file: requirements.txt
          mode: '0644'
      notify:
        - restart service
      tags:
        - never
        - install

    - name: Install python packages
      ansible.builtin.pip:
        requirements: "{{ basedir }}/requirements.txt"
        virtualenv: "{{ venv }}"
      notify:
        - restart service
      tags:
        - never
        - install

    - name: Write configuration
      ansible.builtin.template:
        src: templates/config.yaml.j2
        dest: "{{ confdir }}/config.yaml"
        mode: '0644'
      notify:
        - restart service
      tags:
        - always
        - install
        - config

    - name: Install Systemd script
      become: yes
      ansible.builtin.template:
        src: files/thenose.service.j2
        dest: /etc/systemd/system/thenose.service
        mode: '0700'
        owner: root
        group: root
      notify:
        - reload systemd
        - restart service
      tags:
        - never
        - install

  handlers:
    - name: reload systemd
      become: yes
      ansible.builtin.systemd:
        daemon_reload: yes

    - name: restart service
      become: yes
      ansible.builtin.systemd:
        name: thenose
        enabled: yes
        state: restarted
