---
ansible_host: 192.168.1.100
hostname: nose1

ansible_python_interpreter: /usr/bin/python3

thenose_write_key: aabbccddeeff00112233445566778899                  
thenose_dataset: air-quality
thenose_sample_frequency: 30
thenose_co2_baseline: 0x954e
thenose_tvoc_baseline: 0x9175