name: Lint

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Black Lint
      uses: psf/black@stable

    - name: Lint Ansible Playbook
      uses: ansible/ansible-lint-action@master
      with:
        targets: |
          install.yml
